from pathlib import Path
from PIL import Image, ImageFilter, ImageEnhance

ROOT = Path(__file__).resolve().parents[1]
PHOTO_DIR = ROOT / "assets" / "photos"
INDEX = ROOT / "index.html"

# The current hero assets were intentionally tiny during the first migration.
# Re-render them once at a browser-friendly size, with restrained sharpening.
for i in range(1, 5):
    path = PHOTO_DIR / f"hero-{i:02d}.webp"
    with Image.open(path) as im:
        im = im.convert("RGB")
        target_w = max(im.width, 1600)
        target_h = round(target_w * im.height / im.width)
        if target_w != im.width:
            im = im.resize((target_w, target_h), Image.Resampling.LANCZOS)
        im = im.filter(ImageFilter.UnsharpMask(radius=1.15, percent=145, threshold=2))
        im = ImageEnhance.Contrast(im).enhance(1.025)
        im.save(path, "WEBP", quality=88, method=6)

html = INDEX.read_text(encoding="utf-8")
marker = "/* CRISP HERO OVERRIDE — generated by tools/crisp_hero.py */"
if marker not in html:
    override = r'''
/* CRISP HERO OVERRIDE — generated by tools/crisp_hero.py */
.hero__slide{
  transform:none!important;
  will-change:opacity!important;
  filter:contrast(1.045) saturate(1.035)!important;
  image-rendering:auto;
  backface-visibility:hidden;
}
@keyframes heroCrossfade{
  0%{opacity:0;transform:none}
  4%{opacity:1;transform:none}
  23%{opacity:1;transform:none}
  27%{opacity:0;transform:none}
  100%{opacity:0;transform:none}
}
.hero__bg::after{
  background:
    linear-gradient(90deg,rgba(28,23,66,.54) 0%,rgba(28,23,66,.31) 42%,rgba(28,23,66,.10) 76%,rgba(28,23,66,.06) 100%),
    linear-gradient(180deg,rgba(18,15,48,.05) 0%,rgba(18,15,48,.04) 54%,rgba(18,15,48,.24) 100%)!important;
}
@media(max-width:700px){
  .hero__bg::after{
    background:
      linear-gradient(180deg,rgba(28,23,66,.07) 0%,rgba(28,23,66,.05) 34%,rgba(28,23,66,.26) 69%,rgba(28,23,66,.56) 100%),
      linear-gradient(90deg,rgba(28,23,66,.10),rgba(28,23,66,.02))!important;
  }
  .hero__slide{filter:contrast(1.06) saturate(1.04)!important}
}
'''
    html = html.replace("</style>", override + "\n</style>", 1)
    INDEX.write_text(html, encoding="utf-8")
