from pathlib import Path
import base64, re

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / '.hero-src' / 'final'
PHOTO = ROOT / 'assets' / 'photos'
INDEX = ROOT / 'index.html'

# Rebuild the four hero images from high-resolution originals staged as base64 chunks.
for i in range(1, 5):
    parts = sorted(SRC.glob(f'hero-{i:02d}-*.b64'))
    if not parts:
        raise SystemExit(f'Missing staged hero {i}')
    payload = ''.join(p.read_text(encoding='ascii') for p in parts)
    (PHOTO / f'hero-{i:02d}.webp').write_bytes(base64.b64decode(payload))

html = INDEX.read_text(encoding='utf-8')

# Remove the previous generated override entirely so the new treatment is authoritative.
html = re.sub(
    r'\n?/\* CRISP HERO OVERRIDE — generated by tools/crisp_hero\.py \*/.*?(?=\n</style>)',
    '', html, flags=re.S
)

final_css = r'''

/* FINAL HERO — original-resolution photography + localised text contrast */
.hero__slide{
  transform:none!important;
  filter:none!important;
  image-rendering:auto!important;
  backface-visibility:hidden;
  will-change:opacity!important;
  animation:heroCrossfade 24s linear infinite!important;
}
@keyframes heroCrossfade{
  0%{opacity:0;transform:none}
  2%{opacity:1;transform:none}
  23%{opacity:1;transform:none}
  25%{opacity:0;transform:none}
  100%{opacity:0;transform:none}
}
.hero__bg::after{
  background:
    radial-gradient(ellipse 72% 86% at 14% 70%,
      rgba(24,18,60,.78) 0%,
      rgba(24,18,60,.62) 30%,
      rgba(24,18,60,.34) 48%,
      rgba(24,18,60,.10) 66%,
      rgba(24,18,60,0) 82%),
    linear-gradient(180deg,rgba(15,12,39,.14) 0%,rgba(15,12,39,0) 34%,rgba(15,12,39,.05) 72%,rgba(15,12,39,.18) 100%)!important;
}
.hero h1{
  color:#fff!important;
  text-shadow:0 2px 5px rgba(10,8,28,.58),0 10px 34px rgba(20,16,44,.42)!important;
}
.hero .eyebrow{
  color:#FFD326!important;
  text-shadow:0 2px 10px rgba(10,8,28,.72)!important;
}
.hero>.wrap>p:not(.eyebrow):not(.hero__strip){
  color:rgba(255,255,255,.98)!important;
  text-shadow:0 2px 9px rgba(10,8,28,.78)!important;
}
.hero__strip{
  color:rgba(255,255,255,.96)!important;
  text-shadow:0 2px 8px rgba(10,8,28,.68)!important;
  border-top-color:rgba(255,255,255,.42)!important;
}
@media(max-width:700px){
  .hero__bg::after{
    background:
      linear-gradient(180deg,
        rgba(15,12,39,.10) 0%,
        rgba(15,12,39,.02) 34%,
        rgba(15,12,39,.14) 54%,
        rgba(15,12,39,.58) 72%,
        rgba(15,12,39,.88) 100%)!important;
  }
  .hero h1{ text-shadow:0 2px 4px rgba(10,8,28,.64),0 8px 24px rgba(10,8,28,.48)!important; }
  .hero>.wrap>p:not(.eyebrow):not(.hero__strip){ text-shadow:0 2px 8px rgba(10,8,28,.86)!important; }
}
'''
html = html.replace('\n</style>', final_css + '\n</style>', 1)

# Correct intrinsic dimensions to the actual original artwork and cache-bust the hero files.
for i in range(1, 5):
    html = html.replace(
        f'src="assets/photos/hero-{i:02d}.webp" alt="" width="2048" height="1152"',
        f'src="assets/photos/hero-{i:02d}.webp?v=final-20260905" alt="" width="1672" height="941"'
    )

# Preload only the first hero; the others decode asynchronously during its dwell time.
preload = '<link rel="preload" as="image" href="assets/photos/hero-01.webp?v=final-20260905" type="image/webp">\n'
if 'hero-01.webp?v=final-20260905' not in html.split('</head>',1)[0]:
    html = html.replace('<link rel="manifest" href="site.webmanifest">\n', '<link rel="manifest" href="site.webmanifest">\n' + preload, 1)

INDEX.write_text(html, encoding='utf-8')
